version: "3.3"
services:
  postgres:
    image: "postgres:10.3-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=market
      - POSTGRES_PASSWORD=fuckzap
      - POSTGRES_DB=market_api
volumes:
  postgres:
